<h1>Live Chat License Data</h1>

<form id="license_form" action="<?php echo $block->getFormAction() ?>" method="post">
    <label for="livechat_license_number">License No</label>
    <input name="livechat_license_number" id="livechat_license_number" type="text" data-validate='{"required":true}'><br/>
    <label for="livechat_groups" >Group</label>
    <input name="livechat_groups" id="livechat_groups" type="text"><br/>
    <label for="livechat_params">Params</label>
    <input name="livechat_params"  id="livechat_params" type="text"><br/>
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
    <input type="submit" value="Save" class="primary action">
</form>
<script type="text/x-magento-init">
    {
        "#license_form": {
            "validation": {}
        }
    }
</script>
